### ISSUE TITLE
Plus fonctionnel :(

### ISSUE THREAD

**Issue by deshiloh** [SAWKIT-17/Cyberpunk-2077-mapping-AZERTY-FIX#2]
Hello

ça a l'air de ne plus fonctionner, :( les touches restent pareil qu'en QWERTY

**Comment by TheSawkit** [comment]
La version pour la màj 2.0 est sortie :)
Il faut maintenant aller dans les paramètres et cliquer sur 'Par défaut' pour que le patch s'applique.
Si jamais tu as de nouveau le soucis, n'hésites pas à le partager

**Comment by aviddv1** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Danielrahimi1, @antoineandrieu, @antirek, @michellehuang42, @snatvb, @windmgc, @raffeyang, @omom2002, @MtCoin406, @alexpozdnyakof, @SaadBazaz, @MenesesGHZ, @Pariyat, @gwsystem, @milad-jsx, @bellangerclement, @Lakhankumawat, @devxoul, @oursy, @hxlhxl, @oscarrock, @tagelian, @kazuki-hanai, @Rodrigo-Gil, @clacerda, @chengchaoyin, @BuiltByBrandon, @richardhsueh, @mattsears18, @kevinqmcdonald, @TumTum23, @mateitudose, @valtab, @RichlyElks, @alicedoherty, @hajduakos, @ramazangur, @omkar607, @okradze, @auroraug, @jdichev, @bitcodr, @blakewatters, @intermyr, @Aeternam, @amber12021, @codingbabysix, @3ziek, @luhalvesbr, @arfanliaqat

**Comment by aviddv1** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Abigail6on, @alsenysulla, @randomxiang, @dreampuf, @cowboycodr, @bijoy26, @ningpengtao-coder, @vineetp6, @evenluo, @cmihaylov, @SuplabsYi, @Antropic1, @iksarfo, @maxnth, @lucasmls, @mohitSharma74, @nateqminar, @lucky-verma, @Herbling101, @JacobLinCool, @Msiavashi, @Lil-Late-06xX, @daeranmoth, @GilbertHG, @juabara, @henryzt, @yosriady, @eri2490, @ghsdh3409, @SofwanCoder, @liqwik, @xiangfengsu, @LioCisco, @hassamulhaq, @demiroo, @lipanski, @ioribrn, @m-ddlfngz, @StreetMogu1, @cncolder, @stefan2904, @seonghyeonkimm, @firebuggirl, @mark1yo, @minkj1992, @lljxx1, @nononcentz, @sansx, @Oli8, @sebas5384
